# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://tongyx361.github.io',
                'git_url': 'https://github.com/tongyx361/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.test': { 'nbdev_hello_world.test.foo': ('test.html#foo', 'nbdev_hello_world/test.py'),
                                        'nbdev_hello_world.test.say_hello': ('test.html#say_hello', 'nbdev_hello_world/test.py')}}}
